### ISSUE TITLE
[OSVR-Unity] Failed to create RenderManager.

### ISSUE THREAD

**Issue by fuptup** [OSVR/OSVR-Unity-Rendering#29]
Windows7 Pro SP1 
Geforce GTX970 (373.06) (I've also tried various other drivers 362, 365)
HDK2 1.97 (nothing works with the latest firmware)
OSVR runtime v0.6-1339-g3139e8c

I've been trying to get the HMD to work in Unity for 4 days now. I have managed to get it to work in extended mode with SteamVR but that's all.

Nothing works in DirectMode even though it appears I can switch between extended and direct okay. SteamVR doesn't work (it crashes), non of the RenderManager samples work (and I cannot find the logs for these - the console just runs, displays text I cannot read, then closes immediately), and I can only run stuff in Unity in extended mode and dragging the game window to the HMD (but this renders as though cross-eyed)

I did manage to take a screenshot of the D3D example console before it closed. There are some weird looking values there. Exception addresses maybe?

![osvr d3d example console screeny](https://cloud.githubusercontent.com/assets/22617949/19417106/ca1d64f6-939b-11e6-84ca-4a45320e07d3.jpg)

I've received no response from support so I'm hoping someone here is kind enough to help me out.

Cheers

**Comment by DuFF14** [comment]
Closing as this issue was solved on gitter chat with the following advice:

> - always update to the latest RenderManager DLLs which are included with the Unity packages here: http://access.osvr.com/binary/osvr-unity
> - for those with server crash issues, use a more recent OSVR Runtime from http://access.osvr.com/binary/osvr-sdk-installer
> - I use direct mode config: https://github.com/OSVR/OSVR-Core/blob/master/apps/sample-configs/osvr_server_config.renderManager.HDKv2.0.direct.json
> with a slight change of maxMsBeforeVsync = 3
> - HDK must be in direct mode already for a game to work in direct mode, it won't switch to direct mode automatically
> - if the RenderManager examples work but nothing displays (you keep seeing "Rendering at 90fps..." messages but no image), try switching to extended mode, power cycle  (unplug the power and HMD from beltbox, wait a few seconds, replug), then switch back to direct mode.
> - If USB disconnects between direct mode sessions, power cycle. If it happens frequently, try a different firmware (1.01 or 1.97) http://sensics.com/software/OSVRControl-SW/publish.htm
