### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by demonixis** [OSVR/OSVR-Unity-Rendering#30]
Hi,

It seems that the plugin is incompatible with Linux. We don't have the Direct Mode on Linux but it could be great to have 

- Distortion Correction
- Time Warp (Async?)
- Auto move the window to the HDK screen.

Additionally, it would be good to have a build for both Linux 32 and 64. Even if it's not yet ready.

**Comment by Conzar** [comment]
Just to correct a misunderstand.  Linux has had direct mode for decades.  Its known as using separate x screens per display.  I just want to correct this misunderstanding many Windows developers have about linux.  That direct rendering mode is some new innovative concept.  The reality is, Windows like always, is years behind linux.

**Comment by demonixis** [comment]
Hum I was thinking that the direct mode used by VR headsets was a GPU vendor feature. I don't know if DRM is the same thing as the direct mode feature from NVIDIA GameWorks VR and AMD Liquid VR. In any case, if it's the same thing, it's awesome.

**Comment by ChristophHaag** [comment]
Direct Mode is likely doing a bit more, seeing how it is a requirement for ATW. But since it's all under NDA only the OSVR developers really know and they probably can't say.

The point is that you can get pretty good VR on Linux without it and that it should definitely not be a blocker for Linux support.

**Comment by demonixis** [comment]
Yes, but in all cases we need this plugin for Unity content. Just for the TW, the distortion correction and the window placement.

**Comment by ChristophHaag** [comment]
In case people haven't seen it, I believe https://github.com/OSVR/OSVR-Unity-Rendering/issues/5#issuecomment-253326937 is the only real issue that needs to be solved for this.

**Comment by demonixis** [comment]
Interesting... I'm not a C++ developer, it'll hard to help sorry :/

**Comment by russell-taylor** [comment]
The main things we get from DirectMode are (1) the ability to present textures to the display and have them swap immediately or at the next vsync, and (2) knowledge of when the next vsync is coming.  Graphics card drivers typically buffer an unspecified number of frames before presenting to maximize rendering throughput.  Their VR APIs bypass this, along with any OS-supplied buffering used for transparent overlays and such.  Running on a new screen with Linux, and not running a window manager on that screen, should provide the bypass but I don't yet know about the other two.

In any case, OpenGL with non-DirectMode including TW and distortion correction is available on Linux using RenderManager and indeed the only thing holding it back is #5.

**Comment by demonixis** [comment]
OK thanks for the clarification. I close this issue.

**Comment by Conzar** [comment]
Thanks @russell-taylor !!!
