### ISSUE TITLE
Depth occlusion flicker in 32-bit builds

### ISSUE THREAD

**Issue by jfrank-razer** [OSVR/OSVR-Unity-Rendering#31]
I encountered a perplexing issue while testing 32-bit builds from Unity.  In short, there's a cube that intersects with the ground plane and should be partially occluded by it.  In 64-bit builds, this works fine.  In 32-bit builds, the cube flickers between being partially occluded by the plane and not being occluded at all.  This flickering is visible only in the left eye.  Moving or rotating the cube far enough fixes the problem.

A Unity project to demonstrate the issue is available [here](https://github.com/Razer-OSVR/Personal-JFRANK-OSVR-Unity-x86-build-depth-flicker).  The README in that repository has additional details.

I've observed this on a GTX 1070 and GTX 980, both with patched Win10x64.  I verified that this doesn't appear on the Vive with the SteamVR plugin (hence the supplementary scene).

If this should go in the OSVR/OSVR-Unity project instead, please let me know and I'll move it.

@rpavlik - This is the bug we discussed on our recent call.  Sorry it took so long to get it filed!

**Comment by DuFF14** [comment]
@jfrank-razer I could reproduce in Unity 5.3.5 but not in Unity 5.5.1f1. Perhaps this was a bug in Unity. Are you still seeing it?

**Comment by jfrank-razer** [comment]
Sounds like they fixed it then. You can probably close this and I'll reopen it if I can reproduce the issue. Thanks!

_____________________________
